spring.application.name=Adiyogi-Travels

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
server.port=${PORT:8080}
server.address=0.0.0.0
google.api.key=${GOOGLE_API_KEY}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

app.admin.email=${ADMIN_EMAIL}

# =========================
# Brevo API
# =========================
brevo.api.key=${BREVO_API_KEY}
firebase.service-account-path=secrets/firebase-service-account.json
# Sender email

app.mail.sender-name=Elixway
app.mail.from=noreply@elixway.com
JWT_SECRET=${JWT_SECRET}
JWT_EXPIRATION=${JWT_EXPIRATION}

travelpayouts.api-url=https://api.travelpayouts.com
travelpayouts.token=${TRAVELPAYOUTS_TOKEN}
travelpayouts.marker=${TRAVELPAYOUTS_MARKER}
travelpayouts.host=${TRAVELPAYOUTS_HOST}
