spring.application.name=Adiyogi-Travels

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

google.api.key=${GOOGLE_API_KEY}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

app.admin.email=${ADMIN_EMAIL}

# =========================
# Brevo API
# =========================
brevo.api.key=${BREVO_API_KEY}

# Sender email
app.mail.from=adiyogicabz@gmail.com
JWT_SECRET=${JWT_SECRET}
JWT_EXPIRATION=${JWT_EXPIRATION}