spring.application.name=Adiyogi-Travels
# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:5432/quickbooking
spring.datasource.username=postgres
spring.datasource.password=akashivu
google.api.key=AIzaSyA2cFuK7PcvkCnGBxbkKVstFb0vP1Ue6i4


# JPA settings
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Server port
server.port=8080

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vijaytourstravels6158@gmail.com
spring.mail.password=zewl xzes mdor rjlo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
app.admin.email=vijaytourstravels6158@gmail.com


